import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import clsx from 'clsx';

import './globals.css';

const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx('bg-background min-h-screen font-sans antialiased', fontSans.variable)}>
        {children}
      </body>
    </html>
  );
}
