[package]
name = "maze-runner"
version = "0.1.0"
authors = ["Ladislav Prix <elix78963@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
maze-core  = { path = "../maze-core" }
thiserror = "1.0.61"
