[package]
name = "maze-runner"
version = "0.0.0"
authors = ["Ladislav Prix <elix78963@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
thiserror = "1.0.61"
# local crates
maze-core.workspace = true
