[package]
name = "console"
version = "0.1.0"
authors = ["Ladislav Prix <elix78963@gmail.com>"]
edition = "2018"

[dependencies]
# local crates
maze-core.workspace = true
maze-runner.workspace = true
maze-generator.workspace = true