[package]
name = "console"
version = "0.1.0"
authors = ["Ladislav Prix <elix78963@gmail.com>"]
edition = "2018"

[dependencies]
engine-core  = { path = "../../crates/engine-core" }
engine-runner  = { path = "../../crates/engine-runner" }