[package]
name = "console"
version = "0.1.0"
authors = ["Ladislav Prix <elix78963@gmail.com>"]
edition = "2018"

[dependencies]
maze-core  = { path = "../../crates/maze-core" }
maze-runner  = { path = "../../crates/maze-runner" }