[package]
name = "maze-generator"
version = "0.0.0"
authors = ["Ladislav Prix <elix78963@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rand = "0.9.2"
getrandom = { version = "0.3", features = ["wasm_js"] }
thiserror = "2.0.12"
# local crates
maze-core.workspace = true
maze-runner.workspace = true
